language: java
script: gradle dist
sudo: false

#install:
#- echo sonatypeUsername=none >> gradle.properties
#- echo sonatypePassword=none >> gradle.properties

#after_success:
#- ".travis/publish-results.sh"

#deploy:
 # api_key:
#    secure: CJWhv76T55re6sEhYblukVcOKhr1nP9zZ6bAdvp3nbcjRNcBh5shMj/fq/JaqKos90cTDpTwBn3rnbAtrX24TLU0KX//CzRkzjmYsl3e71Rb5v9MDiOFdw/iZTNZXBRED7fZy6eGqTboWHN0BGAPHBrsypRo8zVdFTuYDMRgsi0=
