language: java
script: gradle dist
sudo: false

deploy:
  provider: releases
  api_key:
    secure: Q1zi1yC4ZbeaY+GtKji/QjVKIDwxMoYkfU7v4RShA1/7oFFgJBSDliv+yCCafsp/y3rQD9er3wNzdUsV8pRBO0TNnYwGPyoepvSjaQRzwGbghx3QHhoBMTvLjEsNnhvX/daMbtYLUHP/6oIkKr2sGEwrNfbBlfvoCe7MSdQ2XFo=
  file:
    - build/distributions/docbook-xslt2-$TRAVIS_TAG.zip
    - build/distributions/docbook-xslt2-$TRAVIS_TAG.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
